def getsims(whichsims):
	sims= np.array([]);	labels= np.array([]); host_mvir= np.array([]); host_mstr= np.array([]); colors= np.array([]); min_vmax=np.array([])
	rvirs= np.array([]); opcs= np.array([]); zords= np.array([]); linst= np.array([]); linst2= np.array([]); has_dmo = np.array([])

	if whichsims=='all':
		sims        = np.array(['m11q_res880'  ,'m11d_res7100','m11e_res7100','m11c_res2100','m11v_res7100'])
		labels      = np.array(['m11q DM+Hydro','m11d'        ,'m11e'        ,'m11c'        ,'m11v'        ])
		host_mvir   = np.array(['1.4e11'       , '2.6e11'     ,'1.4e11'      ,'1.5e11'      ,'2.9e11'      ])
		host_mstr   = np.array(['3.9e8'        ,'3.9e9'       ,'1.5e9'       ,'8.2e8'       ,'2.4e9'       ])
		colors      = np.array([c.orange       ,c.blue        ,c.green       ,c.purple      ,c.brown       ])
		rvirs       = np.array([106.1          ,131.8         ,107.0         ,108.5         ,136.6         ])
		opcs        = np.array([1.0            ,0.65          ,0.65          ,0.65          ,0.65          ])
		zords       = np.array([300            ,250           ,100           ,50            ,10            ])
		linst       = np.array(['-'            ,'--'          ,'--'          ,'--'          ,'--'          ])
		linst2      = np.array(['-.'           ,':'           ,':'           ,':'           ,':'           ])
		has_dmo 	= np.array([True           ,True          ,True          ,False         ,False         ])
		min_vmax    = np.array([1.7            ,4.0           ,4.0           ,2.5           ,4.0           ])

	else:
		if 'm11q' in whichsims:
			sims        = np.append(sims     ,'m11q_res880'  )
			labels      = np.append(labels   ,'m11q DM+Hydro')
			host_mvir   = np.append(host_mvir,'1.4e11'       )
			host_mstr   = np.append(host_mstr,'3.9e8'        )
			colors      = np.append(colors   ,c.orange       )
			rvirs       = np.append(rvirs    ,106.1          )
			opcs        = np.append(opcs     ,1.0            )
			zords       = np.append(zords    ,300            )
			linst       = np.append(linst    ,'-'            )
			linst2      = np.append(linst2   ,'-.'           )
			has_dmo     = np.append(has_dmo  ,True           )
			min_vmax    = np.append(min_vmax ,1.7            )
		if 'm11d' in whichsims:
			sims        = np.append(sims     ,'m11d_res7100')
			labels      = np.append(labels   ,'m11d'        )
			host_mvir   = np.append(host_mvir, '2.6e11'     )
			host_mstr   = np.append(host_mstr,'3.9e9'       )
			colors      = np.append(colors   ,c.blue        )
			rvirs       = np.append(rvirs    ,131.8         )
			opcs        = np.append(opcs     ,0.65          )
			zords       = np.append(zords    ,250           )
			linst       = np.append(linst    ,'--'          )
			linst2      = np.append(linst2   ,':'           )
			has_dmo     = np.append(has_dmo  ,True          )
			min_vmax    = np.append(min_vmax ,4.0           )
		if 'm11e' in whichsims:
			sims        = np.append(sims     ,'m11e_res7100')
			labels      = np.append(labels   ,'m11e'        )
			host_mvir   = np.append(host_mvir,'1.4e11'      )
			host_mstr   = np.append(host_mstr,'1.5e9'       )
			colors      = np.append(colors   ,c.green       )
			rvirs       = np.append(rvirs    ,107.0         )
			opcs        = np.append(opcs     ,0.65          )
			zords       = np.append(zords    ,100           )
			linst       = np.append(linst    ,'--'          )
			linst2      = np.append(linst2   ,':'           )
			has_dmo     = np.append(has_dmo  ,True          )
			min_vmax    = np.append(min_vmax ,4.2           )
		if 'm11c' in whichsims:
			sims        = np.append(sims     ,'m11c_res2100')
			labels      = np.append(labels   ,'m11c'        )
			host_mvir   = np.append(host_mvir,'1.5e11'      )
			host_mstr   = np.append(host_mstr,'8.2e8'       )
			colors      = np.append(colors   ,c.purple      )
			rvirs       = np.append(rvirs    ,108.5         )
			opcs        = np.append(opcs     ,0.65          )
			zords       = np.append(zords    ,50            )
			linst       = np.append(linst    ,'--'          )
			linst2      = np.append(linst2   ,':'           )
			has_dmo     = np.append(has_dmo  ,False         )
			min_vmax    = np.append(min_vmax ,2.5           )
		if 'm11v' in whichsims:
			sims        = np.append(sims     ,'m11v_res7100')
			labels      = np.append(labels   ,'m11v'        )
			host_mvir   = np.append(host_mvir,'2.9e11'      )
			host_mstr   = np.append(host_mstr,'2.4e9'       )
			colors      = np.append(colors   ,c.brown       )
			rvirs       = np.append(rvirs    ,136.6         )
			opcs        = np.append(opcs     ,0.65          )
			zords       = np.append(zords    ,10            )
			linst       = np.append(linst    ,'--'          )
			linst2      = np.append(linst2   ,':'           )
			has_dmo     = np.append(has_dmo  ,False         )
			min_vmax    = np.append(min_vmax ,4.0           )

	return sims,labels,host_mvir,host_mstr,colors,rvirs,opcs,zords,linst,linst2,has_dmo,min_vmax